version: '3.8'

services:
  evals-backend:
    image: your-dockerhub-username/evals-backend:latest
    container_name: evals-backend
    ports:
      - "80:8000"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - evals-network

networks:
  evals-network:
    driver: bridge
